### ISSUE TITLE
Too long lines (E501) fail to be reported when ending with an open triple-quoted string

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#616]
In GitLab by @deubeuliou on Aug 31, 2017, 02:33

*Please describe how you installed Flake8*

```
# pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```{python}
{
  "dependencies": [
    {
      "dependency": "setuptools", 
      "version": "25.1.1"
    }
  ], 
  "platform": {
    "python_implementation": "CPython", 
    "python_version": "2.7.13", 
    "system": "Linux"
  }, 
  "plugins": [
    {
      "plugin": "mccabe", 
      "version": "0.6.1"
    }, 
    {
      "plugin": "pycodestyle", 
      "version": "2.3.1"
    }, 
    {
      "plugin": "pyflakes", 
      "version": "1.5.0"
    }
  ], 
  "version": "3.3.0"
}
```

*Please describe the problem or feature*

Too long lines (E501) fail to be reported when ending open with a triple-quoted string.

*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

`foo.py`:
```{python}
$ cat foo.py 
len("this line if 86 chars long and is not reported.....", "foo bar baz spam egg", """
        some other string""")

len("this line is 86 chars long and is reported.........", """foo bar baz spam egg""",
    "some other string")

```
```{sh}
$ flake8 foo.py 
foo.py:4:80: E501 line too long (86 > 79 characters)
```

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Aug 31, 2017, 05:22

This is a bug in pycodestyle. Please report it to that project (
https://github.com/pycqa/pycodestyle/issues/new).

- Ian

**Comment by asottile** [comment]
In GitLab by @deubeuliou on Aug 31, 2017, 14:30

done: https://github.com/PyCQA/pycodestyle/issues/679

**Comment by asottile** [comment]
In GitLab by @deubeuliou on Aug 31, 2017, 14:30

closed

**Comment by manu2504** [comment]
@asottile the pycodestyle issue you're referring to is an old issue, however the issue persists. I will report it there: https://github.com/PyCQA/pycodestyle/issues/679#issuecomment-1018768562 (they said its flake8 specific though...)
